index:
  path: /:page
  parameters: {page: '?<page>[\d]*'}
  defaults: {page: 1}
  controller: \Src\Controller\DefaultController
  action: indexAction

commentsPage:
  path: /:page/:commentsPage
  parameters: {page: '?<page>[\d]+', commentsPage: '?<commentsPage>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: getChapterCommentsAction

admin:
  path: /admin
  parameters: {}
  controller: \Src\Controller\DefaultController
  action: adminAction

formChapterSelect:
  path: /admin/chapter/select/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: showChapterAction

chapterAdd:
  path: /admin/chapter/add
  parameters: {}
  controller: \Src\Controller\DefaultController
  action: addChapterAction

chapterUpdate:
  path: /admin/chapter/update/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: updateChapterAction

chapterDelete:
  path: /admin/chapter/delete/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: deleteChapterAction

commentSelect:
  path: /admin/comment/select/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: showCommentAction

commentUpdate:
  path: /admin/comment/update/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: updateCommentAction

commentDelete:
  path: /admin/comment/delete/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: deleteCommentAction

# show:
#   path: /show/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: showAction

# delete:
#   path: /delete/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: deleteAction

