show:
  path: /show/:id
  parameters: {id: '[\d]+'}
  controller: Controller\DefaultController
  action: showAction

add:
  path: /add
  parameters: {}
  controller: Controller\DefaultController
  action: addAction

update:
  path: /update/:id
  parameters: {id: '[\d]+'}
  controller: Controller\DefaultController
  action: updateAction

delete:
  path: /delete/:id
  parameters: {id: '[\d]+'}
  controller: Controller\DefaultController
  action: deleteAction

index:
  path: /:page
  parameters: {page: '[\d]*'}
  defaults: {page: 1}
  controller: Controller\DefaultController
  action: indexAction