index:
  path: /:page
  parameters: {page: '?<page>[\d]*'}
  defaults: {page: 1}
  controller: \Src\Controller\DefaultController
  action: indexAction

commentsPage:
  path: /:page/:commentsPage
  parameters: {page: '?<page>[\d]+', commentsPage: '?<commentsPage>[\d]+'}
  controller: \Src\Controller\DefaultController
  action: pageCommentsAction

admin:
  path: /admin
  parameters: {}
  controller: \Src\Controller\DefaultController
  action: adminAction

add:
  path: /add
  parameters: {}
  controller: \Src\Controller\DefaultController
  action: addAction





# show:
#   path: /show/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: showAction



# update:
#   path: /update/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: updateAction

# delete:
#   path: /delete/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: deleteAction

