index:
  path: /
  parameters: {}
  controller: \Src\Controller\PageController
  action: indexAction

chapter:
  path: /chapter/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\PageController
  action: chapterAction

admin:
  path: /admin
  parameters: {}
  controller: \Src\Controller\PageController
  action: adminAction

adminConnexion:
  path: /adminConnexion
  # parameters: {id: '?<id>[\d]+'}
  parameters: {}
  controller: \Src\Controller\PageController
  action: connexionAction

disconnect:
  path: /disconnect
  parameters: {}
  controller: \Src\Controller\PageController
  action: disconnectAction

# indexAsAdmin:
#   path: /indexAdmin
#   parameters: {}
#   controller: \Src\Controller\PageController
#   action: viewBlogAsAdminAction

formChapterSelect:
  path: /admin/chapter/select/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\ChapterController
  action: showChapterAction

chapterAdd:
  path: /admin/chapter/add
  parameters: {}
  controller: \Src\Controller\ChapterController
  action: addChapterAction

chapterUpdate:
  path: /admin/chapter/update/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\ChapterController
  action: updateChapterAction

chapterDelete:
  path: /admin/chapter/delete/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\ChapterController
  action: deleteChapterAction

commentsPage:
  path: /:page/:commentsPage
  parameters: {page: '?<page>[\d]+', commentsPage: '?<commentsPage>[\d]+'}
  controller: \Src\Controller\CommentController
  action: getChapterCommentsAction

commentSignal:
  path: /signal/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\controller\commentController
  action: signalCommentAction

commentPost:
  path: /post/:page
  parameters: {page: '?<page>[\d]+'}
  controller: \Src\Controller\CommentController
  action: postCommentAction

commentSelect:
  path: /admin/comment/select/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\CommentController
  action: showCommentAction

commentUpdate:
  path: /admin/comment/update/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\CommentController
  action: updateCommentAction

commentDelete:
  path: /admin/comment/delete/:id
  parameters: {id: '?<id>[\d]+'}
  controller: \Src\Controller\CommentController
  action: deleteCommentAction
