index:
  path: /:page
  parameters: {page: '?<page>[\d]*'}
  defaults: {page: 1}
  controller: \Src\Controller\DefaultController
  action: indexAction

commentsPage:
  path: /:page/:commentsPage
  parameters: {page: '?<page>[\d]+', commentsPage: '?<commentsPage>[\d]+'}
  defaults: {page: 1, commentsPage: 1}
  controller: \Src\Controller\DefaultController
  action: commentsAction






# show:
#   path: /show/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: showAction

# add:
#   path: /add
#   parameters: {}
#   controller: \Src\Controller\DefaultController
#   action: addAction

# update:
#   path: /update/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: updateAction

# delete:
#   path: /delete/:id
#   parameters: {id: '?<id>[\d]+'}
#   controller: \Src\Controller\DefaultController
#   action: deleteAction

